name: 'saas_revenue_dbt'
version: '1.0.0'
config-version: 2

profile: 'saas_revenue_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  saas_revenue_dbt:
    staging:
      +materialized: view
      +schema: STAGING
      +database: SAAS_REVENUE_DB
    gold:
      +materialized: table
      +schema: GOLD
      +database: SAAS_REVENUE_DB